### ISSUE TITLE
Syncing specials causes errors

### ISSUE THREAD

**Issue by tvgazza911** [romanvm/kodi.tvmaze.scrobbler#13]
When syncing specials errors occur:

TVmaze --> Kodi

Due to TVmaze's numbering of specials, the episode number is _Null_, this causes errors such as the below (full log is attached)

2020-07-25 21:41:13.802 T:10440   ERROR: SQL: [MyVideos116.db] SQLite error SQLITE_ERROR (no such column: None)
                                            Query: select * from episode_view  WHERE (episode_view.idShow = 8) AND (((CAST(episode_view.c12 as DECIMAL(5,1)) = 1)) AND ((CAST(episode_view.c13 as DECIMAL(5,1)) = None)) AND ((episode_view.playCount IS NULL OR episode_view.playCount = 0)))

Kodi --> TVmaze

Due to how specials are handled in the metadata plugin, they will always have the season as 0.

This means that it will always be ignored by the scrobbler as it fails the prepare episodes condition; https://github.com/romanvm/kodi.tvmaze.scrobbler/blob/master/script.tvmaze.scrobbler/libs/scrobbling_service.py#L148

[kodi.log](https://github.com/romanvm/kodi.tvmaze.scrobbler/files/4989010/kodi.log)

**Comment by romanvm** [comment]
I see that there are 2 errors happening at the same time: one in TVmaze scraper and another in TVmaze scrobbler. The one in the scraper is clear for me (I hate Python 2 for it) and I'll fix it ASAP. But I cannot find the reason for the other error because I need a debug log, not a regular one. Please go to Kodi Settings > System, enable Expert mode and then in Logging enable debug logging and component specific logging for JSON-RPC and DATABASE. Then try to reproduce this error and post a full debug log.

**Comment by tvgazza911** [comment]
Hi Roman,

This was actually a log from another user, not myself. However, I've attached my own now
[kodi.log](https://github.com/romanvm/kodi.tvmaze.scrobbler/files/4989853/kodi.log)

I've already written a fix for Kodi --> TVmaze.
For TVmaze --> Kodi I've made it skip the specials for now, rather than error out.

I'm just about to submit a pull request

**Comment by romanvm** [comment]
Yes, now I see that is is the result of an oversight from my side. I totally forgot that specials have number=null on TVmaze, not season.

**Comment by tvgazza911** [comment]
If we were going to provide an (at least temporary) solution to TVmaze --> Kodi special syncing, then one way would be to use the uniqueid property.

Unfortunately, Kodi doesn't support filtering by uniqueid in the _VideoLibrary.GetEpisodes_ request; from my own tests you get:

`2020-07-30 19:02:45.326 T:16392   DEBUG: JSONRPC: Incoming request: {"params": {"filter": {"and": [{"operator": "is", "field": "playcount", "value": "0"}, {"operator": "isnot", "field": "uniqueid", "value": null}]}, "tvshowid": 1, "properties": ["season", "episode", "uniqueid", "playcount", "tvshowid"]}, "jsonrpc": "2.0", "method": "VideoLibrary.GetEpisodes", "id": "1"}`
`2020-07-30 19:02:45.327 T:16392   DEBUG: JSONRPC: Invalid property "value" in type List.Filter.Rule`
`2020-07-30 19:02:45.328 T:16392   DEBUG: JSONRPC: Value does not match extended type List.Filter.Rule of type List.Filter.Rule.Episodes`
`2020-07-30 19:02:45.328 T:16392   DEBUG: JSONRPC: Array element at index 1 does not match in type and`
`2020-07-30 19:02:45.328 T:16392   DEBUG: JSONRPC: Invalid property "and" in type`
`2020-07-30 19:02:45.328 T:16392   DEBUG: JSONRPC: Value does not match extended type List.Filter.Rule of type List.Filter.Rule.Episodes`
`2020-07-30 19:02:45.331 T:16392   DEBUG: script.tvmaze.scrobbler [v.0.2.1] - medialibrary_api.py:48 - JSON-RPC reply:
                                            {u'error': {u'code': -32602,
                                                        u'data': {u'method': u'VideoLibrary.GetEpisodes',
                                                                  u'stack': {u'message': u'Received value does not match any of the union type definitions',
                                                                             u'name': u'filter',
                                                                             u'property': {u'type': u'string'},
                                                                             u'type': u'object'}},
                                                        u'message': u'Invalid params.'},
                                             u'id': u'1',
                                             u'jsonrpc': u'2.0'}`

This [thread ](https://forum.kodi.tv/showthread.php?tid=196279) corroborates that; "That functionality is currently not part of the JSON-RPC API so you'd have to do it yourself by retrieving all episodes and then going through them looking for the uniqueid you want."

As that says, a workaround of returning all episodes with playcount of 0 for that show, and then manually filtering by the uniqueid would work (and I have tested this), however I don't know how much this weighs on performance.
