### ISSUE TITLE
Syncing always updates TVmaze watch date

### ISSUE THREAD

**Issue by tvgazza911** [romanvm/kodi.tvmaze.scrobbler#15]
When syncing to TVmaze, the watch date that is stored on TVmaze will always be updated, regardless of it is already marked as watched in TVmaze.

This is used to drive statistics on particular time periods (last week/month/year) and is therefore a problem.

As can be seen [here](https://www.tvmaze.com/users/173874/gazza913/watched), each watched episode has the watch date for it; the statistics where it is used can be found [here](https://www.tvmaze.com/users/173874/gazza913/stats).

**P.S.** I have already made changes that would fix this, however it relies on #14 being accepted, therefore I will wait until that has been accepted before making another pull request

**Comment by romanvm** [comment]
Yes, looks like my compromise solution has its flaws. I tried to minimize requests to TVmaze API but if it is not a big issue, then the addon can check episode statuses before actual update.

**Comment by tvgazza911** [comment]
The proposed changes I've made does indeed check the actual status on TVmaze prior to adding it to the list to update.

I've also tested it with various scenarios.

**Comment by romanvm** [comment]
@tvgazza911 I have created a fix for it too that does not require extra requests to TVmaze API. The only thing I cannot figure is how TVmaze stores times. I assumed that posix timestamps should be in UTC timezone but something is wrong. See the attached screenshot.
![image](https://user-images.githubusercontent.com/1595560/89990093-89940c00-dc8a-11ea-945f-c5a221d3d444.png)
So either the watched list does not respect user's timezone on TVmaze or I'm doing something wrong.

**Comment by tvjan** [comment]
posix timestamps are timezone independent.
‎It's the amount of seconds since midnight 1970 UTC

**Comment by romanvm** [comment]
Yes, but then I guess this is a TVmaze display issue because I'm sending `1597217819` timestamp and my timezone on TVmaze is "+02:00 Europe/Kiev" (it's +3 actually because of DST).

**Comment by tvdavid** [comment]
> ![image](https://user-images.githubusercontent.com/1595560/89990093-89940c00-dc8a-11ea-945f-c5a221d3d444.png)
> So either the watched list does not respect user's timezone on TVmaze or I'm doing something wrong.

Ah, this does not indicate a problem: indeed we simply don't localize the timestamp on that page, it's displayed in UTC. I'll make a note to clarify this, although I'm not sure yet how - should it be in the timezone of the user who watched the episode, or in the timezone of the user who's viewing the page? Sorry for the confusion!

**Comment by romanvm** [comment]
Thanks for the clarification. I'll close this issue then because it has been fixed.
