### ISSUE TITLE
Timezone Invalid Params

### ISSUE THREAD

**Issue by tvgazza911** [romanvm/kodi.tvmaze.scrobbler#19]
Just did a simple 'Sync all shows' and received an error.

Settings.GetSettingValue
```
json_reply = {u'error': {u'code': -32602, u'message': u'Invalid params.'},
                                             u'id': u'1',
                                             u'jsonrpc': u'2.0'}
                                            method = u'Settings.GetSettingValue'
                                            params = {u'setting': u'locale.timezone'}
```

I don't know exactly what the issue is here, but I've attached the log that has JSON-RPC logging enabled.
[kodi.log](https://github.com/romanvm/kodi.tvmaze.scrobbler/files/5131589/kodi.log)

FYI I'm on the latest 0.2.2 version.

**Comment by romanvm** [comment]
A very strange error. It is not reproduced on my dev system. I'll investigate it.

**Comment by romanvm** [comment]
Ok, looks like timezone setting in Kodi is a Linux thing. I need a different way to obtain user's timezone from Python.
