### ISSUE TITLE
Syntax error in upsert_episode

### ISSUE THREAD

**Issue by tvgazza911** [romanvm/kodi.tvmaze.scrobbler#20]
On pulling episodes from TVmaze, when the upsert_episode function is called, it results in the following syntax error:

Error Type: <class 'sqlite3.OperationalError'>
Error Contents: near "ON": syntax error

Full Log is attached
[kodi.log](https://github.com/romanvm/kodi.tvmaze.scrobbler/files/5143961/kodi.log)

**Comment by romanvm** [comment]
Looks like Python 2.7 in Windows builds is linked against an ancient SQlite version that doesn't support ON CONFLICT statement.

**Comment by tvgazza911** [comment]
I've confirmed that Kodi 18.8 uses an embedded version of Python, rather than the system one.

Specifically v2.7.13 of python & v3.17 of SQLite (which is less than the required v3.24).

Unfortunately there doesn't seem to be any way around this...

Even if I overwrite the Python files to use a later version of Python (as confirmed in the logs), it still uses the same version of SQLite due to the SQLite DLL.

Also, if I overwrite sqlite3.dll with the newer one, it causes Kodi to crash on startup.

Only the newer 19.0 builds, which is still in pre-release use an updated version of python (v3.7.x), however that drops a lot of support and would put us onto a unstable build.
