### ISSUE TITLE
Invalid value -1 for marked_at

### ISSUE THREAD

**Issue by tvdavid** [romanvm/kodi.tvmaze.scrobbler#21]
I tracked down one of the "Unable to push episodes for show "The Good Place": Failed to update 1 episodes" errors. Turns out the scrobbler is sending `-1` for `marked_at`, but that's not a valid value in the API - it should be an epoch or `0` for unknown.

**Comment by romanvm** [comment]
@tvdavid the scrobbler never explicitly sends -1 as a timestamp. Currently an episode timestamp is determined based on `dateadded` (for acquired) or `lastplayed` (for watched) time strings in Kodi database taking into account user's timezone. Could you attach a Kodi debug log with JSON-RPC component enabled recorded while it happens?

**Comment by tvdavid** [comment]
I don't have access to this Kodi system right now, but I'll check it out soon.

How do I enable JSON-RPC recording?

**Comment by romanvm** [comment]
It's in `Settings > System > Logging - > Enable Component-specific logging`. And in `Specify Enable Component-specific` logging select JSON-RPC and database.

**Comment by tvdavid** [comment]
Found it! Looks like my library had an entry that somehow got borked. 

```
                                                                       {u'dateadded': u'1970-01-01 00:59:59',
                                                                        u'episode': 9,
                                                                        u'episodeid': 149,
                                                                        u'label': u'4x09. The Answer',
                                                                        u'lastplayed': u'',
                                                                        u'playcount': 0,
                                                                        u'season': 4,
                                                                        u'tvshowid': 12},
                                                                       {u'dateadded': u'2019-11-28 09:23:36',
                                                                        u'episode': 9,
                                                                        u'episodeid': 150,
                                                                        u'label': u'4x09. The Answer',
                                                                        u'lastplayed': u'',
                                                                        u'playcount': 0,
                                                                        u'season': 4,
                                                                        u'tvshowid': 12},
```

And this was sent as

```
                                                      {u'episode': 9, u'marked_at': -1, u'season': 4, u'type': 1},
                                                      {u'episode': 9, u'marked_at': 1574411016, u'season': 4, u'type': 1},
```

`1970-01-01 00:59:59` will likely be parsed into an epoch of `-1`. I don't know how common such borked entries are, but probably best to change any value of <0 to 0.

**Comment by romanvm** [comment]
Thanks, I'll do that.
