### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by SweetthD3ViL** [romanvm/kodi.tvmaze.scrobbler#24]
Hello Roman, 

Firstly thank you for the addon and for the undoubtedly hard work! 

I just installed it on one of my Kodi running on Archlinux and setup with a shared MySql database located on a NAS. 

When trying to log the addon with my TvMaze account using the email address - as I do not get the option of the QR code or link (like mentioned on the TvMaze post/website) I get an error - see below the log.

Looking forward to your reply.

====================================================================================================
                                                                                       Diagnostic info
                                            ----------------------------------------------------------------------------------------------------
                                            Exception type  : <class 'requests.exceptions.SSLError'>
                                            Exception value : HTTPSConnectionPool(host='api.tvmaze.com', port=443): Max retries exceeded with url: /v1/auth/start (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
                                            System info     : ('Linux', 'Archlinux', '5.8.7-arch1-1', '#1 SMP PREEMPT Sat, 05 Sep 2020 12:31:32 +0000', 'x86_64', '')
                                            Python version  : 2.7.18 (default, Sep  5 2020, 11:17:26)  [GCC 10.2.0]
                                            OS info         : Busy
                                            Kodi version    : 18.8 (18.8.0) Git:20200813-nogitfound
                                            File            : /home/sweetth/.kodi/addons/script.module.requests/lib/requests/adapters.py:514
                                            sys.argv        : ['script.py']
                                            ----------------------------------------------------------------------------------------------------
                                            sys.path:
                                            ['',
                                             '/home/sweetth/.kodi/addons/script.tvmaze.scrobbler',
                                             '/home/sweetth/.kodi/addons/script.module.certifi/lib',
                                             '/home/sweetth/.kodi/addons/script.module.chardet/lib',
                                             '/home/sweetth/.kodi/addons/script.module.dateutil/lib',
                                             '/home/sweetth/.kodi/addons/script.module.idna/lib',
                                             '/home/sweetth/.kodi/addons/script.module.kodi-six/libs',
                                             '/home/sweetth/.kodi/addons/script.module.pyqrcode/lib',
                                             '/home/sweetth/.kodi/addons/script.module.pyxbmct/lib',
                                             '/home/sweetth/.kodi/addons/script.module.requests/lib',
                                             '/home/sweetth/.kodi/addons/script.module.six/lib',
                                             '/home/sweetth/.kodi/addons/script.module.urllib3/lib',
                                             '/usr/lib/python27.zip',
                                             '/usr/lib/python2.7',
                                             '/usr/lib/python2.7/plat-linux2',
                                             '/usr/lib/python2.7/lib-tk',
                                             '/usr/lib/python2.7/lib-old',
                                             '/usr/lib/python2.7/lib-dynload',
                                             '/usr/lib/python2.7/site-packages',
                                             '/usr/lib/python2.7/site-packages/gtk-2.0']
                                            ----------------------------------------------------------------------------------------------------
                                            Code context:
                                              512:             if isinstance(e.reason, _SSLError):
                                              513:                 # This branch is for urllib3 v1.22 and later.
                                              514:>                raise SSLError(e, request=request)
                                              515: 
                                              516:             raise ConnectionError(e, request=request)
                                            
                                            ----------------------------------------------------------------------------------------------------
                                            Global variables:
                                            BaseAdapter = <class 'requests.adapters.BaseAdapter'>
                                            CaseInsensitiveDict = <class 'requests.structures.CaseInsensitiveDict'>
                                            ClosedPoolError = <class 'urllib3.exceptions.ClosedPoolError'>
                                            ConnectTimeout = <class 'requests.exceptions.ConnectTimeout'>
                                            ConnectTimeoutError = <class 'urllib3.exceptions.ConnectTimeoutError'>
                                            ConnectionError = <class 'requests.exceptions.ConnectionError'>
                                            DEFAULT_CA_BUNDLE_PATH = '/home/sweetth/.kodi/addons/script.module.certifi/lib/certifi/cacert.pem'
                                            DEFAULT_POOLBLOCK = False
                                            DEFAULT_POOLSIZE = 10
                                            DEFAULT_POOL_TIMEOUT = None
                                            DEFAULT_RETRIES = 0
                                            HTTPAdapter = <class 'requests.adapters.HTTPAdapter'>
                                            HTTPResponse = <class 'urllib3.response.HTTPResponse'>
                                            InvalidProxyURL = <class 'requests.exceptions.InvalidProxyURL'>
                                            InvalidSchema = <class 'requests.exceptions.InvalidSchema'>
                                            InvalidURL = <class 'requests.exceptions.InvalidURL'>
                                            LocationValueError = <class 'urllib3.exceptions.LocationValueError'>
                                            MaxRetryError = <class 'urllib3.exceptions.MaxRetryError'>
                                            NewConnectionError = <class 'urllib3.exceptions.NewConnectionError'>
                                            PoolManager = <class 'urllib3.poolmanager.PoolManager'>
                                            ProtocolError = <class 'urllib3.exceptions.ProtocolError'>
                                            ProxyError = <class 'requests.exceptions.ProxyError'>
                                            ReadTimeout = <class 'requests.exceptions.ReadTimeout'>
                                            ReadTimeoutError = <class 'urllib3.exceptions.ReadTimeoutError'>
                                            Response = <class 'requests.models.Response'>
                                            ResponseError = <class 'urllib3.exceptions.ResponseError'>
                                            Retry = <class 'urllib3.util.retry.Retry'>
                                            RetryError = <class 'requests.exceptions.RetryError'>
                                            SOCKSProxyManager = <function SOCKSProxyManager at 0x7f75900d9a50>
                                            SSLError = <class 'requests.exceptions.SSLError'>
                                            TimeoutSauce = <class 'urllib3.util.timeout.Timeout'>
                                            _HTTPError = <class 'urllib3.exceptions.HTTPError'>
                                            _ProxyError = <class 'urllib3.exceptions.ProxyError'>
                                            _SSLError = <class 'urllib3.exceptions.SSLError'>
                                            _basic_auth_str = <function _basic_auth_str at 0x7f759011bbd0>
                                            basestring = <type 'basestring'>
                                            extract_cookies_to_jar = <function extract_cookies_to_jar at 0x7f759010b750>
                                            extract_zipped_paths = <function extract_zipped_paths at 0x7f75900fa550>
                                            get_auth_from_url = <function get_auth_from_url at 0x7f759010fd50>
                                            get_encoding_from_headers = <function get_encoding_from_headers at 0x7f759010f350>
                                            os = <module 'os' from '/usr/lib/python2.7/os.pyo'>
                                            parse_url = <function parse_url at 0x7f75900f6bd0>
                                            prepend_scheme_if_needed = <function prepend_scheme_if_needed at 0x7f759010fcd0>
                                            proxy_from_url = <function proxy_from_url at 0x7f75ac1387d0>
                                            select_proxy = <function select_proxy at 0x7f759010fa50>
                                            socket = <module 'socket' from '/usr/lib/python2.7/socket.pyo'>
                                            urldefragauth = <function urldefragauth at 0x7f759010fe50>
                                            urlparse = <function urlparse at 0x7f7590eb4b50>
                                            ----------------------------------------------------------------------------------------------------
                                            Local variables:
                                            cert = None
                                            chunked = False
                                            conn = <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f75dff91410>
                                            e = MaxRetryError('HTTPSConnectionPool(host=\'api.tvmaze.com\', port=443): Max retries exceeded with url: /v1/auth/start (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')],)",),))',)
                                            proxies = OrderedDict()
                                            request = <PreparedRequest [POST]>
                                            self = <requests.adapters.HTTPAdapter object at 0x7f75900cae50>
                                            stream = False
                                            timeout = <urllib3.util.timeout.Timeout object at 0x7f75901a1fd0>
                                            url = '/v1/auth/start'
                                            verify = True
                                            ====================================================================================================
                                            **************************************** End diagnostic info ***************************************
2020-09-11 11:04:40.036 T:140142914344512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: HTTPSConnectionPool(host='api.tvmaze.com', port=443): Max retries exceeded with url: /v1/auth/start (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
                                            Traceback (most recent call last):
                                              File "/home/sweetth/.kodi/addons/script.tvmaze.scrobbler/script.py", line 40, in <module>
                                                main()
                                              File "/home/sweetth/.kodi/addons/script.tvmaze.scrobbler/script.py", line 35, in main
                                                action()
                                              File "/home/sweetth/.kodi/addons/script.tvmaze.scrobbler/libs/scrobbling_service.py", line 89, in authorize_addon
                                                token, confirm_url = tvmaze.start_authorization(email)
                                              File "/home/sweetth/.kodi/addons/script.tvmaze.scrobbler/libs/tvmaze_api.py", line 185, in start_authorization
                                                response = _call_user_api(AUTH_START_PATH, 'post', authenticate=False, json=data)
                                              File "/home/sweetth/.kodi/addons/script.tvmaze.scrobbler/libs/tvmaze_api.py", line 163, in _call_user_api
                                                response = _send_request(url, method, auth=auth, **requests_kwargs)
                                              File "/home/sweetth/.kodi/addons/script.tvmaze.scrobbler/libs/tvmaze_api.py", line 118, in _send_request
                                                response = method_func(url, auth=auth, **requests_kwargs)
                                              File "/home/sweetth/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 581, in post
                                                return self.request('POST', url, data=data, json=json, **kwargs)
                                              File "/home/sweetth/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/sweetth/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/sweetth/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 514, in send
                                                raise SSLError(e, request=request)
                                            SSLError: HTTPSConnectionPool(host='api.tvmaze.com', port=443): Max retries exceeded with url: /v1/auth/start (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
                                            -->End of Python script error report<--

**Comment by romanvm** [comment]
Please attach your full debug log as a file to the ticket.

**Comment by SweetthD3ViL** [comment]
Hello Roman,

Thank you for the prompt reply, see full log attached. 
[kodi.log](https://github.com/romanvm/kodi.tvmaze.scrobbler/files/5208403/kodi.log)

**Comment by tvgazza911** [comment]
Hi SweetthD3ViL,

This was a problem with the API itself.

David has since put in place a workaround; see [here](https://www.tvmaze.com/threads/4441/ssl-cert-error-since-two-hours-ago-ssl-certificateverifyfailed-certificate-verify-failed-certificate-has-expired#60519).

Please can you check if you still have this issue?

**Comment by romanvm** [comment]
I have also disabled certificate verification in the addon.

**Comment by SweetthD3ViL** [comment]
Thank you for your reply and prompt actions. 

It is working great and currently updating. 

Thanks!

**Comment by romanvm** [comment]
Ok, I'm closing it then.
