### ISSUE TITLE
Scrobble using filenames

### ISSUE THREAD

**Issue by Dracoster** [romanvm/kodi.tvmaze.scrobbler#25]
Some people don't archive every episode of every shows they watch, and use the file manager to start the episodes not in the library. Having the addon scrobble by filename (i.e. show.title.sXXeYY.*) would be severely helpfull.

**Comment by romanvm** [comment]
The addon uses library metadata to correctly match episodes between Kodi and TVmaze. Re-implementing the whole Kodi's scraping functionaity at the addon level does not make much sense. If a user doesn't use Kodi medialibrary then they should accept all the limitations of their approach.
